# Generated by Django 3.0.3 on 2020-05-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='type',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='value',
        ),
        migrations.AddField(
            model_name='measure',
            name='actividad',
            field=models.CharField(default='1', max_length=20, verbose_name='actividad'),
        ),
        migrations.AddField(
            model_name='measure',
            name='cedula',
            field=models.IntegerField(default=1, verbose_name='cedula'),
        ),
        migrations.AddField(
            model_name='measure',
            name='estrato',
            field=models.CharField(default='1', max_length=2, verbose_name='estrato'),
        ),
        migrations.AddField(
            model_name='measure',
            name='nombre',
            field=models.CharField(default='1', max_length=20, verbose_name='nombre'),
        ),
    ]
